### PR TITLE
Add missing vector pattern

### PR DESCRIPTION
**Pull request by mnieper**
This is an erratum as discussed on the mailing list.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Shall I publish a new draft or wait?

**Comment by mnieper** [comment]
Hi Arthur,

It is an erratum, no new draft, so I think you can publish it immediately.
Or what do you mean?

Thanks,

Marc

Am Do., 21. Dez. 2023 um 21:04 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

**Comment by arthurgleckler** [comment]
Sorry, I was confused because I was just about to send you my regular reminder about SRFI 247, which is, of course, still a draft.

I'll publish the erratum now.  Thanks.

**Comment by arthurgleckler** [comment]
Merged, labeled, and pushed.

Sorry for the confusion.

**Comment by mnieper** [comment]
Thank you!

Am Do., 21. Dez. 2023 um 21:42 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

**Pull request merged**
